### ISSUE TITLE
Нет проверки на дату начала трудоустройства и дату окончания.

### ISSUE THREAD

**Issue by Gopher723** [TheDanz/ResumeCreator#3]
1. Запускаем приложение, нажимаем на кнопку "Создать новое резюме"
2. Заполняем все поля
2. Переходим на вкладку "Опыт работы" и заполняем период работы
![image](https://user-images.githubusercontent.com/90313106/145792146-21d147ab-676d-4282-95ef-8b3594647837.png)
3. Нажимаем на кнопку "Готово"
4. На появившемся экране нажимаем на кнопку "Открыть резюме в отдельном окне"
5. Видим, что в разделе "Опыт работы" некорректно указаны данные(с 08.10.2021 по 19.12.2018)
![image](https://user-images.githubusercontent.com/90313106/145792810-b647cde2-2c9e-4aeb-9ddc-d916d6b7c120.png)
Ожидаемый результат: программа выдаст ошибку и скажет, что дата окончания трудоустройства не может быть "меньше" даты принятия на работу.

**Comment by missiamnq** [comment]
done :)
