### ISSUE TITLE
Нет проверки на формат номера телефона(на длину вводимой строки)

### ISSUE THREAD

**Issue by Diasha01** [TheDanz/ResumeCreator#5]
1. Запускаем приложение, нажимаем на кнопку "Создать новое резюме"
2. Заполняем все поля, нажимаем кнопку "Готово", на появившемся экране нажимаем на кнопку "Открыть резюме в отдельном окне"
![image](https://user-images.githubusercontent.com/90570776/145799555-ccd9e285-a7da-4312-ab87-953919632a38.png)
![image](https://user-images.githubusercontent.com/90570776/145799602-b9a0c06f-bfae-43b4-a988-abfe34d81dab.png)

Видим, что не производится проверка на формат номера телефона, введённая некорректно строка записывается в резюме
Ожидаемое поведение: программа выдаст ошибку и попросит изменить формат номера телефона

**Comment by Gopher723** [comment]
👍🏻
