### ISSUE TITLE
Нет проверки на возраст того, кто подаёт резюме

### ISSUE THREAD

**Issue by Diasha01** [TheDanz/ResumeCreator#7]
1. Запускаем приложение, нажимаем на кнопку "Создать новое резюме"
2. Заполняем все поля, нажимаем кнопку "Готово", на появившемся экране нажимаем на кнопку "Открыть резюме в отдельном окне"
![image](https://user-images.githubusercontent.com/90570776/145802025-99f2bb62-cbde-47b9-8708-347a13c27327.png)
![image](https://user-images.githubusercontent.com/90570776/145802005-8dac88bb-2843-4102-b9f9-3e73e0879f70.png)

Ожидаемое поведение: программа выдаст ошибку и попросит сменить дату (ему должно быть не менее 14 и не более 100 лет)

**Comment by missiamnq** [comment]
done :)
